// This file is automatically generated. Do not edit it directly.
import { createClient } from '@supabase/supabase-js';
import type { Database } from './types';

const SUPABASE_URL = "https://cuyqueeuzpitvmcoeing.supabase.co";
const SUPABASE_PUBLISHABLE_KEY = "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJzdXBhYmFzZSIsInJlZiI6ImN1eXF1ZWV1enBpdHZtY29laW5nIiwicm9sZSI6ImFub24iLCJpYXQiOjE3NTQxMzY4OTUsImV4cCI6MjA2OTcxMjg5NX0.SSbo7R1EFEuyOI4hEX80s2D3ykytw8vrzm98uTVav98";

// Import the supabase client like this:
// import { supabase } from "@/integrations/supabase/client";

export const supabase = createClient<Database>(SUPABASE_URL, SUPABASE_PUBLISHABLE_KEY, {
  auth: {
    storage: localStorage,
    persistSession: true,
    autoRefreshToken: true,
  }
});